<a href="https://colab.research.google.com/github/vijaypsk/datascience/blob/master/Workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  **Object creation**

In [9]:
import numpy as np
import pandas as pd

dates=pd.date_range('20190201',periods=8)
print(dates)
df=pd.DataFrame(np.random.randn(8,4),index=dates,columns=list('PQRS'))
print(df)

DatetimeIndex(['2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04',
               '2019-02-05', '2019-02-06', '2019-02-07', '2019-02-08'],
              dtype='datetime64[ns]', freq='D')
                   P         Q         R         S
2019-02-01  1.545921 -0.427641  0.754031 -0.737076
2019-02-02 -1.132558 -0.904429 -0.006168 -1.582717
2019-02-03 -1.485594  0.588557 -0.323705 -0.691924
2019-02-04  0.111342  1.663647 -0.426254  0.931046
2019-02-05 -0.385556 -1.311037  0.543090 -0.490022
2019-02-06 -0.792559 -0.210042  0.742540  0.643610
2019-02-07  1.982872  0.746250  1.518987 -0.507316
2019-02-08  2.908960  0.532508 -0.152549 -1.145115


In [26]:
df2=pd.DataFrame({'A':1.,'B':pd.Timestamp('20190819'),'C':pd.Series(1.3,index=list(range(4)),dtype='float32'),'D':np.array([3.2]*4,dtype='float32'),'E':pd.Categorical(['test','train','test','train']),'F':'bar'})
print(df2)
print(df2.dtypes)
print(df2.F)

     A          B    C    D      E    F
0  1.0 2019-08-19  1.3  3.2   test  bar
1  1.0 2019-08-19  1.3  3.2  train  bar
2  1.0 2019-08-19  1.3  3.2   test  bar
3  1.0 2019-08-19  1.3  3.2  train  bar
A           float64
B    datetime64[ns]
C           float32
D           float32
E          category
F            object
dtype: object
0    bar
1    bar
2    bar
3    bar
Name: F, dtype: object


#  **Viewing Data**

In [33]:
print(df.head())
print(df.tail(2))
print(df.index)
print(df.columns)
print(df.to_numpy())
print(df2.to_numpy())

                   P         Q         R         S
2019-02-01  1.545921 -0.427641  0.754031 -0.737076
2019-02-02 -1.132558 -0.904429 -0.006168 -1.582717
2019-02-03 -1.485594  0.588557 -0.323705 -0.691924
2019-02-04  0.111342  1.663647 -0.426254  0.931046
2019-02-05 -0.385556 -1.311037  0.543090 -0.490022
                   P         Q         R         S
2019-02-07  1.982872  0.746250  1.518987 -0.507316
2019-02-08  2.908960  0.532508 -0.152549 -1.145115
DatetimeIndex(['2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04',
               '2019-02-05', '2019-02-06', '2019-02-07', '2019-02-08'],
              dtype='datetime64[ns]', freq='D')
Index(['P', 'Q', 'R', 'S'], dtype='object')
[[ 1.54592099 -0.42764144  0.75403054 -0.73707591]
 [-1.1325577  -0.90442872 -0.00616799 -1.58271722]
 [-1.4855942   0.58855665 -0.3237047  -0.6919236 ]
 [ 0.11134237  1.66364672 -0.42625364  0.93104607]
 [-0.38555587 -1.31103681  0.54309021 -0.49002229]
 [-0.79255929 -0.2100419   0.74254043  0.64361018]


In [38]:
print(df.describe())
print(df.T)
print(df.sort_index(axis=1,ascending=False))
print(df.sort_values(by='R'))

   2019-02-01  2019-02-02  2019-02-03  ...  2019-02-06  2019-02-07  2019-02-08
P    1.545921   -1.132558   -1.485594  ...   -0.792559    1.982872    2.908960
Q   -0.427641   -0.904429    0.588557  ...   -0.210042    0.746250    0.532508
R    0.754031   -0.006168   -0.323705  ...    0.742540    1.518987   -0.152549
S   -0.737076   -1.582717   -0.691924  ...    0.643610   -0.507316   -1.145115

[4 rows x 8 columns]
                   S         R         Q         P
2019-02-01 -0.737076  0.754031 -0.427641  1.545921
2019-02-02 -1.582717 -0.006168 -0.904429 -1.132558
2019-02-03 -0.691924 -0.323705  0.588557 -1.485594
2019-02-04  0.931046 -0.426254  1.663647  0.111342
2019-02-05 -0.490022  0.543090 -1.311037 -0.385556
2019-02-06  0.643610  0.742540 -0.210042 -0.792559
2019-02-07 -0.507316  1.518987  0.746250  1.982872
2019-02-08 -1.145115 -0.152549  0.532508  2.908960
                   P         Q         R         S
2019-02-04  0.111342  1.663647 -0.426254  0.931046
2019-02-03 -1.485594  

# **Selection**

In [46]:
print(df['R'])
print(df[0:3])
print(df.loc[dates[0]])
print(df.loc[:,['P','R']])

2019-02-01    0.754031
2019-02-02   -0.006168
2019-02-03   -0.323705
2019-02-04   -0.426254
2019-02-05    0.543090
2019-02-06    0.742540
2019-02-07    1.518987
2019-02-08   -0.152549
Freq: D, Name: R, dtype: float64
                   P         Q         R         S
2019-02-01  1.545921 -0.427641  0.754031 -0.737076
2019-02-02 -1.132558 -0.904429 -0.006168 -1.582717
2019-02-03 -1.485594  0.588557 -0.323705 -0.691924
P    1.545921
Q   -0.427641
R    0.754031
S   -0.737076
Name: 2019-02-01 00:00:00, dtype: float64
                   P         R
2019-02-01  1.545921  0.754031
2019-02-02 -1.132558 -0.006168
2019-02-03 -1.485594 -0.323705
2019-02-04  0.111342 -0.426254
2019-02-05 -0.385556  0.543090
2019-02-06 -0.792559  0.742540
2019-02-07  1.982872  1.518987
2019-02-08  2.908960 -0.152549
